repos:
- repo: https://github.com/psf/black
  rev: 22.10.0
  hooks:
  - id: black
    args:
    - --line-length=79
    - --quiet
    - --safe
    - --skip-string-normalization
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v4.3.0
  hooks:
  - id: double-quote-string-fixer
  - id: trailing-whitespace
  - id: end-of-file-fixer
  - id: debug-statements
    language_version: python3.11
- repo: https://github.com/pycqa/flake8
  rev: 5.0.4
  hooks:
  - id: flake8
    language_version: python3.11
    additional_dependencies:
    - flake8-bugbear
